In [ ]:
import numpy as np
data = np.array([1,2,3,4,5])
np.mean(data)

3.0

In [ ]:
np.median(data)

3.0

In [ ]:
np.min(data)

1

In [ ]:
np.max(data)

5

In [ ]:
std_dev = np.std(data)

In [ ]:
print(std_dev)

1.4142135623730951


In [ ]:
np.sum(data)

15

In [9]:
reshaped_data = data.reshape((5,1))

In [10]:
print(reshaped_data)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [11]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [12]:
concatenated = np.concatenate((array1,array2))

In [13]:
print(concatenated)

[1 2 3 4 5 6]


In [14]:
numbers = np.linspace(0,10,5)

In [15]:
print(numbers)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
range_data = np.arange(0,10,2)

In [17]:
print(range_data)

[0 2 4 6 8]
